# following sql queries are performed on the sakila database which is the default sample database in mysql.
#refer to the image provided, for understanding of the database tables .


#1. Retrieve the total revenue generated for each film category.
select fc.category_id,sum(p.amount) as revenue from film_category fc join film f on fc.film_id=f.film_id join inventory i on f.film_id=i.film_id join rental r on i.inventory_id=r.inventory_id join payment p on r.rental_id=p.rental_id group by fc.category_id;


#2. Determine the count of rentals for each customer.
select c.first_name,c.customer_id,count(r.rental_id) from rental r join customer c on r.customer_id=c.customer_id group by c.customer_id;

#3. Calculate the average rental duration (in days) for each film.
select title,avg(rental_duration) from film group by title;

#4. Find the total revenue generated for each month.
select month(p.payment_date),sum(p.amount) from payment p group by month(p.payment_date);

#5. Determine the total revenue generated by each store.
select s.store_id, sum(p.amount) from payment p join rental r on p.rental_id=r.rental_id join inventory i on r.inventory_id=i.inventory_id join store s on i.store_id=s.store_id group by s.store_id;

#6. Calculate the count of rentals handled by each staff member.
select s.staff_id, count(r.rental_id) from staff s join rental r on s.staff_id=r.staff_id group by s.staff_id;

#7. Compute the average rental rate for each film category.
select fc.category_id,avg(f.rental_rate) from film_category fc join film f on fc.film_id=f.film_id group by fc.category_id;

#8. Determine the count of rentals for each film.
select f.film_id,f.title, count(r.rental_id) from film f join inventory i on f.film_id=i.film_id join rental r on i.inventory_id=r.inventory_id group by f.film_id,f.title;

#9. Retrieve the total revenue generated for each city.
select ci.city_id,ci.city,sum(amount) from payment p join customer c on p.customer_id=c.customer_id join address a on c.address_id=a.address_id join city ci on a.city_id=ci.city_id group by ci.city_id,ci.city;

#10. Calculate the count of rentals for each film language.
select l.language_id,l.name,count(r.rental_id) from language l join film f on l.language_id=f.language_id join inventory i on f.film_id=i.film_id join rental r on i.inventory_id=r.inventory_id group by l.language_id,l.name;



